### ISSUE TITLE
Run Program Button

### ISSUE THREAD

**Issue by Luiss112** [MobilePixels/Tetra#1]
**System Version:**
 Windows 11

**Error Screenshot:**

![{7C8429B8-DC04-45D6-8E7A-E5FA54D621DE}](https://github.com/user-attachments/assets/65cbb664-e4d0-4032-8dd6-629e9f663ecc)

**Description:**
 If i want to add a "Action Button" to run a program i cant find any program i have on my pc...

**Comment by mp-jarvie** [comment]
@Luiss112

1. The preset buttons of Tetra software are strictly matched. Can you try searching again? A fuzzy match was performed. Then make your selection. 
<img width="567" alt="image" src="https://github.com/user-attachments/assets/0195047d-d8c1-4a4b-839b-66cd07f4794d">

2. If there is still no match, you can also manually select the software shortcut or executable program (exe) in the installation directory to open through the open File function. This is suitable for some green software or software that does not create shortcuts.
