### ISSUE TITLE
Touch not working when multiple screens connected

### ISSUE THREAD

**Issue by stephanp2002** [MobilePixels/Tetra#4]
**System Version:**

Windows 11
**Error Screenshot:**

**Description:**

When I have multiple screens connected it takes the touch of the tetra keyboard on the main display rather than on the Tetra screen itself.

**Comment by zfengMP** [comment]
Please try the following steps:

Open Control Panel

Then change the view to "Small icons"

Then select Tablet PC Settings (assuming cable and/or driver (https://www.mobilepixels.us/pages/download-drivers) installed):

Then click on Setup

Then choose Touch input

Then follow the onscreen instructions to complete the calibration.
